package ru.aisa.rgd.ws.exeption;

public class ServiceCode 
{
	
	public static final int
	ERR_UNDEFINED = -1,
	ERR_OK = 0,
	ERR_TEMPLATE_LOADING = 1,
	ERR_OKATO_EMPTY = 2,
	ERR_DOCUMENT_SAVING = 3,
	ERR_DOCUMENT_PARSING = 4,
	ERR_STATIONID_EMPTY = 5,
	ERR_TEMPLATE_EMPTY = 6,
	ERR_STATEMENT_EXECUTION = 7,
	ERR_ROADID_EMPTY = 8,
	ERR_WAYPART_EMPTY = 9,
	ERR_SRORED_PROCEDURE = 10,
	ERR_ADMINISTRATION_EMPTY = 11,
	ERR_RIVER_EMPTY = 12,	
	ERR_ACTIVITY_KIND_EMPTY = 13,
	ERR_GRUZ_EMPTY = 14,
	ERR_VAGSOB_EMPTY = 15,
	ERR_DIC_OBJECTS_EMPTY = 16,
	ERR_PEREG_MS_EMPTY = 17,
	ERR_UP_EMPTY = 18,
	ERR_STATION_OKPO_KOD_EMPTY = 19,
	ERR_OKPO_CODE_EMPTY = 20,
	ERR_STATION_CODE_EMPTY =21,
	ERR_INTERCEPTOR_SGN_ERROR = 22;	

	

}
